server:
  context-path: /admin/module
  port: 9090

spring:  
  datasource:
      url: jdbc:mysql://localhost/admin-module
      username: root
      password: root123 #123456
      driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  jpa:
    show-sql: true
  redis:
    host: 192.168.99.100 # Redis server host.
    password: # Login password of the redis server.
    database: 0
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 0 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
    port: 6379 # Redis server port.
    timeout: 0
  cache:
    cache-names: admin:module